"""empty message

Revision ID: 3bcbb7973633
Revises: ac0a426342a6
Create Date: 2022-01-10 04:19:28.247259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bcbb7973633'
down_revision = 'ac0a426342a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order', sa.Column('orders2', shop.customers.models.JsonEcodedDict(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order', 'orders2')
    # ### end Alembic commands ###
