"""migracion inicial

Revision ID: 40361fe6702d
Revises: 
Create Date: 2022-01-09 10:17:37.932613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40361fe6702d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('f_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'f_name')
    # ### end Alembic commands ###
