"""empty message

Revision ID: 4aeae6068de4
Revises: c900b4ed8c4f
Create Date: 2022-01-10 04:25:54.346786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeae6068de4'
down_revision = 'c900b4ed8c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order', sa.Column('orders2', sa.String(length=20), nullable=True))
    op.add_column('customer_order', sa.Column('orders3', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order', 'orders3')
    op.drop_column('customer_order', 'orders2')
    # ### end Alembic commands ###
