"""empty message

Revision ID: 69585f6448cb
Revises: aceace1b3661
Create Date: 2022-01-09 10:34:16.937243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69585f6448cb'
down_revision = 'aceace1b3661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('f_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'f_name')
    # ### end Alembic commands ###
