"""empty message

Revision ID: 8c768c3bd6c4
Revises: 3bcbb7973633
Create Date: 2022-01-10 04:21:27.794554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c768c3bd6c4'
down_revision = '3bcbb7973633'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order', sa.Column('orders2', shop.customers.models.JsonEcodedDict(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order', 'orders2')
    # ### end Alembic commands ###
