"""empty message

Revision ID: 90bebebf2b89
Revises: 4aeae6068de4
Create Date: 2022-01-10 04:26:35.035821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90bebebf2b89'
down_revision = '4aeae6068de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order', 'orders3')
    op.drop_column('customer_order', 'orders2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order', sa.Column('orders2', sa.VARCHAR(length=20), nullable=True))
    op.add_column('customer_order', sa.Column('orders3', sa.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
