"""empty message

Revision ID: a708eb639974
Revises: 69585f6448cb
Create Date: 2022-01-09 10:35:02.452791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a708eb639974'
down_revision = '69585f6448cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'f_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('f_name', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
