"""empty message

Revision ID: a80734553451
Revises: 6a875aa58610
Create Date: 2022-01-10 04:24:12.541253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80734553451'
down_revision = '6a875aa58610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order', sa.Column('orders2', shop.customers.models.JsonEcodedDict(), nullable=True))
    op.add_column('customer_order', sa.Column('orders3', shop.customers.models.JsonEcodedDict(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order', 'orders3')
    op.drop_column('customer_order', 'orders2')
    # ### end Alembic commands ###
