"""migracion inicial

Revision ID: aceace1b3661
Revises: 40361fe6702d
Create Date: 2022-01-09 10:22:22.088514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aceace1b3661'
down_revision = '40361fe6702d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'f_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('f_name', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
