"""empty message

Revision ID: c7e26e49c385
Revises: 8c768c3bd6c4
Create Date: 2022-01-10 04:22:50.549010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e26e49c385'
down_revision = '8c768c3bd6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_order', sa.Column('orders3', shop.customers.models.JsonEcodedDict(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_order', 'orders3')
    # ### end Alembic commands ###
